// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gsy/store/pkg/common/database"
	"github.com/gsy/store/pkg/user/adapters/repository"
	"github.com/gsy/store/pkg/user/application"
	"github.com/gsy/store/pkg/user/ports"
)

// Injectors from wire.go:

func InitializeUserServer() (ports.HttpServer, error) {
	db, err := database.GetDatabaseConnection()
	if err != nil {
		return ports.HttpServer{}, err
	}
	repoImpl := repository.NewRepository(db)
	applicationApplication := application.NewApplication(repoImpl)
	httpServer := ports.NewHttpServer(applicationApplication)
	return httpServer, nil
}
